In [1]:
from matplotlib import pyplot as plt
import numpy as np
import cv2

In [56]:
class Image:
    
    def __init__(self, name, image=None, path=None):
        self.name = name
        self.get_image(image, path)
        
        
    def get_image(self, image, path):
        print(image)
        if image != None:
            self.image = image
            print('Loaded image')
        elif path:
            self.get_image_from_path(path)
            print('Loaded image from path')
        else:
            print('Empty image')
            
    
    def get_image_from_path(self, path):
        img = cv2.imread(path)
        self.image = img[:,:,::-1]
        
    
    def mirror(self):
        self.image = cv2.flip(self.image, 1)
    

    def show(self):
        plt.title(self.name)
        plt.imshow(self.image)
        
        
    def set_name(self, name):
        self.name = name

In [57]:
class Eye(Image):
    
    def __init__(self, name_face, image_face, side='right'):
        self.name_face = name_face
        self.image_face = image_face
        self.side = side
        super().__init__(name_face+'_'+side, self.get_eye())

        
    def get_eye(self, amplitude=0.45, height=0.1, wide=0.1):
        face_image = self.image_face
        if self.side == 'right':
            image_eye = face_image[round(face_image.shape[0] * height):round(face_image.shape[0] * (height + amplitude)),
                       round(face_image.shape[1] * wide):round(face_image.shape[1] * (amplitude + wide))]
        else:
            image_eye = face_image[round(face_image.shape[0] * height):round(face_image.shape[0] * (height + amplitude)),
                       round(face_image.shape[1] * (1 - (amplitude + wide))):round(face_image.shape[1] * (1 - wide))]
        return image_eye
    
        

In [58]:
class Face(Image):
    
    def __init__(self, name, image=None, path=None):
        super().__init__(name, image, path)
        self.get_eyes()
        

    def get_eyes(self):
        
        self.eye1 = Eye(name_face=self.name,
                        image_face=self.image,
                        side='right')
        
        self.eye2 = Eye(name_face=self.name,
                        image_face=self.image,
                        side='left')
        

In [59]:
path='../data/test/profile_test/front6.jpg'

In [60]:
face1 = Face('face1', path=path)

None
Loaded image from path
[[[243 229 220]
  [246 232 223]
  [242 228 219]
  ...
  [ 69  24  21]
  [ 76  35  33]
  [102  61  59]]

 [[254 240 231]
  [255 248 239]
  [254 240 231]
  ...
  [ 78  30  28]
  [ 74  33  31]
  [ 74  33  31]]

 [[250 236 227]
  [255 244 235]
  [254 240 231]
  ...
  [101  53  51]
  [ 69  25  22]
  [ 90  46  43]]

 ...

 [[255 238 226]
  [255 241 229]
  [248 230 220]
  ...
  [236 161 121]
  [243 168 129]
  [248 170 131]]

 [[241 223 211]
  [245 227 215]
  [250 232 222]
  ...
  [243 169 132]
  [248 172 136]
  [251 173 135]]

 [[243 225 213]
  [251 233 221]
  [254 236 226]
  ...
  [247 173 136]
  [246 172 135]
  [246 171 132]]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [61]:
face1.eye1.name